(function(){
'use strict';
const TW5={};
const KEY='tineworld_v5_slots';
const W=192,H=120,CH=16,TILE=32;
const BIOMES=['forest','desert','snow','jungle','plains','beach','river','mountain'];
const COLORS={grass:'#4e9b52',forest:'#3e8647',desert:'#d9bd63',snow:'#dcecff',jungle:'#28784b',plains:'#78ad55',beach:'#e9d18b',river:'#2f86c7',mountain:'#7d8389',cave:'#252a31',stone:'#777f87','ore':'#8f67d9'};
const ITEMS={
 wood:{n:'Wood',i:'🪵',max:64},stone:{n:'Stone',i:'🪨',max:64},pickaxe:{n:'Pickaxe',i:'⛏️',max:1},ore:{n:'Iron Ore',i:'⛏️',max:64},coal:{n:'Coal',i:'⚫',max:64},sand:{n:'Sand',i:'🟨',max:64},snow:{n:'Snow',i:'❄️',max:64},plank:{n:'Plank',i:'🟫',max:64},glass:{n:'Glass',i:'🔳',max:32},food:{n:'Apple',i:'🍎',max:32},meat:{n:'Meat',i:'🥩',max:16},bread:{n:'Bread',i:'🍞',max:16},torch:{n:'Torch',i:'🔦',max:32},door:{n:'Door',i:'🚪',max:16},window:{n:'Window',i:'🪟',max:32},chest:{n:'Chest',i:'📦',max:16},chair:{n:'Chair',i:'🪑',max:16},stair:{n:'Stair',i:'🪜',max:32},slab:{n:'Slab',i:'▰',max:32},sword:{n:'Sword',i:'⚔️',max:1},axe:{n:'Axe',i:'🪓',max:1},spear:{n:'Spear',i:'🔱',max:1},bow:{n:'Bow',i:'🏹',max:1},shield:{n:'Shield',i:'🛡️',max:1},helmet:{n:'Helmet',i:'⛑️',max:1},armor:{n:'Armor',i:'🥋',max:1},boots:{n:'Boots',i:'🥾',max:1},fish:{n:'Fish',i:'🐟',max:16},coin:{n:'Coin',i:'🪙',max:999},treasure:{n:'Treasure',i:'💎',max:16}
};
const BLOCKS={plank:'plank',stone:'stone',glass:'glass',door:'door',window:'window',chest:'chest',chair:'chair',stair:'stair',slab:'slab',torch:'torch'};
let canvas,ctx,raf=0,last=0,keys={},touch={x:0,y:0};
let S=null;
function el(id){return document.getElementById(id)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function hash(x,y,seed){let n=(x*374761393+y*668265263+seed*1442695041)|0;n=(n^(n>>>13))*1274126177|0;return ((n^(n>>>16))>>>0)/4294967295}
function noise(x,y,seed){let x0=Math.floor(x),y0=Math.floor(y),xf=x-x0,yf=y-y0;let a=hash(x0,y0,seed),b=hash(x0+1,y0,seed),c=hash(x0,y0+1,seed),d=hash(x0+1,y0+1,seed);let u=xf*xf*(3-2*xf),v=yf*yf*(3-2*yf);return a+(b-a)*u+((c+(d-c)*u)-(a+(b-a)*u))*v}
function biomeAt(x,y,seed){let n=noise(x/24,y/24,seed),m=noise((x+500)/48,(y-200)/48,seed+17);if(n<.13)return 'river';if(n<.2)return 'beach';if(m>.82)return 'snow';if(m>.68)return 'desert';if(m<.18)return 'jungle';if(n>.84)return 'mountain';if(n>.58)return 'forest';return 'plains'}
function terrainAt(x,y,seed){let b=biomeAt(x,y,seed);let h=noise(x/12,y/12,seed+91);if(b==='river')return h<.3?'river':'beach';if(b==='mountain')return h<.35?'stone':(h>.8?'ore':'mountain');if(b==='forest'||b==='jungle')return h>.78?'forest':'grass';if(b==='desert')return h>.82?'stone':'sand';if(b==='snow')return h>.8?'stone':'snow';if(b==='beach')return 'sand';return h>.86?'stone':'grass'}
function makeMap(seed){let map=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>terrainAt(x,y,seed)));for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(hash(x,y,seed+33)>.982&&map[y][x]!=='river')map[y][x]='cave'}return map}
function invDefault(){let a=Array.from({length:36},()=>null);[['wood',24],['stone',18],['ore',6],['food',8],['torch',8],['sword',1],['axe',1],['bow',1],['shield',1],['plank',12]].forEach((v,i)=>a[i]={id:v[0],qty:v[1],dur:100});return a}
function fresh(name='World 1'){let seed=(Date.now()+Math.floor(Math.random()*99999))>>>0;return{name,seed,map:makeMap(seed),x:W/2|0,y:H/2|0,z:0,dir:1,hp:100,maxhp:100,hunger:100,stamina:100,temp:20,day:1,time:480,weather:'clear',inventory:invDefault(),hotbar:[0,1,2,3,4,5,6,7,8],selected:0,equipment:{helmet:null,armor:null,boots:null},blocks:[],entities:[],npcs:[],animals:[],enemies:[],loot:[],quests:[{id:1,text:'Collect 20 wood',goal:20,type:'wood',done:0,reward:50},{id:2,text:'Defeat 3 enemies',goal:3,type:'kills',done:0,reward:80},{id:3,text:'Find the dungeon',goal:1,type:'dungeon',done:0,reward:150}],kills:0,coins:10,fall:0,spawned:false,waypoints:[{x:W/2,y:H/2,n:'Home'}],copied:null,vehicle:null,weatherTimer:0,chat:[],onlineReady:true,stats:{blocks:0,shots:0,days:1},dungeon:{x:W-25,y:H-22,found:false,boss:false},ruins:[],treasures:[],villages:[],chests:[],boss:null,breeding:0,saveAt:Date.now()}}
function ensureS(){if(!S)S=fresh()}
function saveSlots(){try{let all=JSON.parse(localStorage.getItem(KEY)||'{}');let idx=S.slot||0;S.saveAt=Date.now();all[idx]=S;localStorage.setItem(KEY,JSON.stringify(all));setStatus('💾 Saved '+S.name)}catch(e){setStatus('⚠️ Save failed')}}
function loadSlot(i){let all={};try{all=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){};S=all[i]||fresh('World '+(i+1));S.slot=i;seedWorld();setStatus('🌍 '+S.name+' loaded • Seed '+S.seed);renderUI()}
function seedWorld(){if(!S.map||S.map.length!==H)S.map=makeMap(S.seed);normalize();if(['river','cave'].includes(S.map[S.y]?.[S.x])){for(let r=1;r<12;r++){let found=false;for(let dy=-r;dy<=r&&!found;dy++)for(let dx=-r;dx<=r&&!found;dx++){let nx=clamp(S.x+dx,1,W-2),ny=clamp(S.y+dy,1,H-2),t=S.map[ny]?.[nx];if(t&&!['river','cave'].includes(t)){S.x=nx;S.y=ny;found=true}}if(found)break}}if(!S.spawned){spawnAll();S.spawned=true}}
function normalize(){
  if(!S||typeof S!=='object')S=fresh('World 1');
  S.name=S.name||'World 1';
  S.seed=Number.isFinite(Number(S.seed))?Number(S.seed):((Date.now()>>>0));
  S.map=Array.isArray(S.map)&&S.map.length===H?S.map:makeMap(S.seed);
  S.x=Number.isFinite(Number(S.x))?clamp(Number(S.x),1,W-2):Math.floor(W/2);
  S.y=Number.isFinite(Number(S.y))?clamp(Number(S.y),1,H-2):Math.floor(H/2);
  S.dir=S.dir===-1?-1:1; S.hp=Number.isFinite(Number(S.hp))?S.hp:100; S.maxhp=S.maxhp||100;
  S.hunger=Number.isFinite(Number(S.hunger))?S.hunger:100; S.stamina=Number.isFinite(Number(S.stamina))?S.stamina:100;
  S.temp=Number.isFinite(Number(S.temp))?S.temp:20; S.day=S.day||1; S.time=Number.isFinite(Number(S.time))?S.time:480;
  S.weather=S.weather||'clear'; S.anim=S.anim||{type:'idle',t:0,dir:S.dir}; S.blocking=!!S.blocking; S.fall=0;
  S.inventory=Array.isArray(S.inventory)?S.inventory:invDefault(); while(S.inventory.length<36)S.inventory.push(null); S.inventory.length=36;
  S.hotbar=Array.isArray(S.hotbar)?S.hotbar:[0,1,2,3,4,5,6,7,8]; while(S.hotbar.length<9)S.hotbar.push(0);
  S.selected=Math.max(0,Math.min(8,Number(S.selected)||0)); S.equipment=S.equipment||{helmet:null,armor:null,boots:null};
  S.blocks=S.blocks||[];S.npcs=S.npcs||[];S.animals=S.animals||[];S.enemies=S.enemies||[];S.loot=S.loot||[];S.quests=S.quests||[];S.waypoints=S.waypoints||[];
  S.stats=S.stats||{blocks:0,shots:0,days:1};S.coins=Number.isFinite(Number(S.coins))?Number(S.coins):10;S.kills=S.kills||0;S.weatherTimer=S.weatherTimer||0;S.breeding=S.breeding||0;S.chat=S.chat||[];
  S.dungeon=S.dungeon||{x:W-25,y:H-22,found:false,boss:false}; if(!Number.isFinite(S.dungeon.x))S.dungeon.x=W-25;if(!Number.isFinite(S.dungeon.y))S.dungeon.y=H-22;
  if(!S.spawned){spawnAll();S.spawned=true}
}
function spawnAll(){S.npcs=[];S.animals=[];S.enemies=[];S.villages=[];S.ruins=[];S.treasures=[];for(let v=0;v<3;v++){let x=12+Math.floor(hash(v,5,S.seed)*(W-24)),y=12+Math.floor(hash(v,17,S.seed)*(H-24));S.villages.push({x,y,name:['Oakvale','Sunrest','Frostmere'][v]});for(let i=0;i<4;i++)S.npcs.push({x:x+(i%2)*2,y:y+Math.floor(i/2)*2,name:['Mira','Tomas','Luna','Bram'][i],role:i===0?'merchant':'villager',home:{x,y},t:0})}for(let i=0;i<28;i++){let p=freeSpot();S.animals.push({x:p.x,y:p.y,type:['deer','cow','chicken','boar'][i%4],t:Math.random()*9,energy:100,sex:i%2})}for(let i=0;i<18;i++){let p=freeSpot();S.enemies.push({x:p.x,y:p.y,type:['goblin','wolf','skeleton'][i%3],hp:40,max:40,cd:0,flash:0})}for(let i=0;i<4;i++){let p=freeSpot();S.ruins.push({x:p.x,y:p.y,found:false})}for(let i=0;i<5;i++){let p=freeSpot();S.treasures.push({x:p.x,y:p.y,found:false})}}
function freeSpot(){for(let n=0;n<200;n++){let x=2+Math.floor(Math.random()*(W-4)),y=2+Math.floor(Math.random()*(H-4));if(!['river','cave','mountain'].includes(S.map[y][x])&&Math.hypot(x-S.x,y-S.y)>10&&!S.blocks.some(b=>b.x===x&&b.y===y))return{x,y}}return{x:10,y:10}}
function tile(x,y){if(x>=0&&y>=0&&x<W&&y<H)return S.map[y][x];return terrainAt(x,y,S.seed)}
function solidTile(t){return ['river','mountain','stone','cave'].includes(t)}
function blockAt(x,y){return S.blocks.find(b=>b.x===x&&b.y===y)}
function blocked(x,y){return solidTile(tile(x,y))||!!blockAt(x,y)||S.enemies.some(e=>e.x===x&&e.y===y)}
function setStatus(s){let e=el('twFixStatus');if(e)e.textContent=s}
function itemCount(id){return S.inventory.reduce((n,s)=>n+(s&&s.id===id?s.qty:0),0)}
function addItem(id,qty){let def=ITEMS[id];if(!def)return;let left=qty;for(let s of S.inventory)if(s&&s.id===id&&s.qty<def.max){let q=Math.min(left,def.max-s.qty);s.qty+=q;left-=q;if(!left)return}for(let i=0;i<S.inventory.length&&left;i++)if(!S.inventory[i]){let q=Math.min(left,def.max);S.inventory[i]={id,qty:q,dur:100};left-=q}if(left)setStatus('🎒 Inventory full')}
function removeItem(id,qty){let left=qty;for(let i=S.inventory.length-1;i>=0&&left;i--)if(S.inventory[i]?.id===id){let q=Math.min(left,S.inventory[i].qty);S.inventory[i].qty-=q;left-=q;if(!S.inventory[i].qty)S.inventory[i]=null}return left===0}
function selectedItem(){let i=S.hotbar[S.selected]??0;return S.inventory[i]||null}
function move(dx,dy){let speed=S.vehicle==='horse'||S.vehicle==='car'?2:1;dx*=speed;dy*=speed;let nx=S.x+dx,ny=S.y+dy;if(!blocked(nx,ny)){if(speed===2){let mx=S.x+Math.sign(dx),my=S.y+Math.sign(dy);if(blocked(mx,my))return}S.x=clamp(nx,-100000,100000);S.y=clamp(ny,-100000,100000);S.time=(S.time+2)%1440;S.hunger=Math.max(0,S.hunger-.06);S.stamina=Math.max(0,S.stamina-(S.vehicle?0.05:.15));S.stats.days=S.day;S.anim={type:'walk',t:0};renderUI()}}
function jump(){if(S.fall===0&&S.stamina>8){S.fall=1;S.stamina-=8;S.anim={type:'jump',t:0};setStatus('🦘 Jump!')}
}
function mine(){let p=front();let t=tile(p.x,p.y),b=blockAt(p.x,p.y);S.anim={type:'mine',t:0};if(b){let id=b.type==='plank'?'plank':b.type;if(b.type==='chest'){openChest(b);return}S.blocks=S.blocks.filter(q=>q!==b);addItem(id,1);S.stats.blocks++;setStatus('⛏️ Broke '+(ITEMS[id]?.n||id));saveSlots();return}if(t==='forest'){addItem('wood',2);S.map[p.y][p.x]='grass'}else if(t==='stone'||t==='mountain'){addItem('stone',2);S.map[p.y][p.x]='grass'}else if(t==='ore'){addItem('ore',2);S.map[p.y][p.x]='stone'}else if(t==='sand'){addItem('sand',2);S.map[p.y][p.x]='beach'}else if(t==='snow'){addItem('snow',2);S.map[p.y][p.x]='plains'}else{setStatus('⛏️ Nothing useful there');return}questUpdate('wood',itemCount('wood'));saveSlots();renderUI()}
function front(){return{x:clamp(S.x+S.dir,0,W-1),y:S.y}}
function build(){let p=front(),item=selectedItem();if(!item){setStatus('🧱 Select a block in the hotbar');return}if(!BLOCKS[item.id]){setStatus('🧱 Select a building block');return}if(blocked(p.x,p.y)){setStatus('🧱 Blocked');return}S.blocks.push({x:p.x,y:p.y,type:item.id,rot:S.rot||0});removeItem(item.id,1);S.stats.blocks++;S.anim={type:'build',t:0};setStatus('🧱 Built '+ITEMS[item.id].n);saveSlots();renderUI()}
function preview(){let p=front();if(canvas&&ctx){let cam=camera();ctx.save();ctx.globalAlpha=.45;ctx.fillStyle='#fff';ctx.fillRect((p.x-cam.x)*TILE+2,(p.y-cam.y)*TILE+2,TILE-4,TILE-4);ctx.restore()}}
function rotate(){S.rot=((S.rot||0)+1)%4;setStatus('🔄 Rotation '+(S.rot*90)+'°')}
function copyBuild(){let p=front(),b=blockAt(p.x,p.y);if(!b){setStatus('📋 Stand next to a block to copy it');return}S.copied={type:b.type,rot:b.rot||0};setStatus('📋 Copied '+b.type)}
function pasteBuild(){if(!S.copied){setStatus('📋 Nothing copied');return}let p=front();if(blocked(p.x,p.y)){setStatus('📋 Space blocked');return}if(!removeItem(S.copied.type,1)){setStatus('📋 Need '+ITEMS[S.copied.type].n);return}S.blocks.push({x:p.x,y:p.y,type:S.copied.type,rot:S.copied.rot});saveSlots();renderUI()}
function attack(){let e=S.enemies.filter(q=>Math.hypot(q.x-S.x,q.y-S.y)<2.2).sort((a,b)=>Math.hypot(a.x-S.x,a.y-S.y)-Math.hypot(b.x-S.x,b.y-S.y))[0];S.anim={type:'attack',t:0};if(!e){setStatus('⚔️ Swing');return}let it=selectedItem(),dmg=it?.id==='sword'?24:it?.id==='axe'?18:it?.id==='spear'?30:10;let crit=Math.random()<.14;dmg*=crit?2:1;e.hp-=dmg;e.knock=1.1;S.stamina=Math.max(0,S.stamina-4);e.flash=.2;setStatus((crit?'💥 CRITICAL! ':'⚔️ Hit ')+dmg+' damage');if(e.hp<=0){S.enemies=S.enemies.filter(q=>q!==e);S.kills++;S.coins+=10;addItem(Math.random()<.4?'meat':'ore',1);questUpdate('kills',S.kills);setStatus('☠️ Enemy defeated! Loot gained.')}saveSlots();renderUI()}
function shoot(){let bow=itemCount('bow')||selectedItem()?.id==='bow';if(!bow){setStatus('🏹 Need a bow');return}let target=S.enemies.filter(e=>Math.hypot(e.x-S.x,e.y-S.y)<10).sort((a,b)=>Math.hypot(a.x-S.x,a.y-S.y)-Math.hypot(b.x-S.x,b.y-S.y))[0];S.anim={type:'shoot',t:0};S.stats.shots++;if(target){let dmg=32*(Math.random()<.12?2:1);target.hp-=dmg;setStatus('🏹 Arrow hit for '+dmg);if(target.hp<=0){S.enemies=S.enemies.filter(q=>q!==target);S.kills++;S.coins+=15;addItem('meat',1)}}else setStatus('🏹 No target in range');questUpdate('kills',S.kills);saveSlots();renderUI()}
function block(){S.blocking=!S.blocking;setStatus(S.blocking?'🛡️ Shield raised':'🛡️ Shield lowered')}
function eat(){let id=itemCount('bread')?'bread':itemCount('food')?'food':itemCount('meat')?'meat':null;if(!id){setStatus('🍳 No food');return}removeItem(id,1);let gain=id==='bread'?35:id==='meat'?25:20;S.hunger=clamp(S.hunger+gain,0,100);S.hp=clamp(S.hp+8,0,S.maxhp);S.anim={type:'eat',t:0};setStatus('🍎 Ate '+ITEMS[id].n);saveSlots();renderUI()}
function cook(){if(itemCount('meat')>=1&&itemCount('wood')>=1){removeItem('meat',1);removeItem('wood',1);addItem('bread',1);setStatus('🍳 Cooked food')}else setStatus('🍳 Need meat + wood')}
function craft(id){let recipes={pickaxe:{need:{wood:3,stone:2},out:['pickaxe',1]},sword:{need:{wood:1,ore:3},out:['sword',1]},spear:{need:{wood:2,ore:2},out:['spear',1]},bow:{need:{wood:3,plank:2},out:['bow',1]},shield:{need:{wood:4,stone:2},out:['shield',1]},door:{need:{plank:4},out:['door',1]},window:{need:{glass:2,plank:2},out:['window',2]},chest:{need:{plank:8},out:['chest',1]},chair:{need:{plank:3},out:['chair',1]},stair:{need:{plank:4},out:['stair',2]},slab:{need:{plank:3},out:['slab',2]},torch:{need:{wood:1,coal:1},out:['torch',4]},glass:{need:{sand:2},out:['glass',1]},bread:{need:{food:2,wood:1},out:['bread',1]},helmet:{need:{ore:4},out:['helmet',1]},armor:{need:{ore:8},out:['armor',1]},boots:{need:{ore:4},out:['boots',1]}}[id];if(!recipes)return;for(let k in recipes.need)if(itemCount(k)<recipes.need[k]){setStatus('🔨 Need more '+ITEMS[k].n);return}for(let k in recipes.need)removeItem(k,recipes.need[k]);addItem(...recipes.out);setStatus('🔨 Crafted '+ITEMS[id].n);saveSlots();renderUI()}
function equip(slot){let s=S.inventory.findIndex(v=>v&&['helmet','armor','boots'].includes(v.id));if(s<0){setStatus('🛡️ No armor in inventory');return}let id=S.inventory[s].id;if(S.equipment[slot])addItem(S.equipment[slot].id,1);S.equipment[slot]=S.inventory[s];S.inventory[s]=null;setStatus('🛡️ Equipped '+ITEMS[id].n);saveSlots();renderUI()}
function interact(){let n=S.npcs.find(n=>Math.hypot(n.x-S.x,n.y-S.y)<3);if(!n){setStatus('💬 No NPC nearby');return}if(n.role==='merchant'){if(itemCount('ore')>=2){removeItem('ore',2);addItem('coin',20);setStatus('🪙 Merchant trade: 2 ore → 20 coins')}else setStatus('🛒 '+n.name+': Bring me 2 ore for 20 coins.')}else{setStatus('📜 '+n.name+': '+(n.t===0?'Explore, gather and survive.':'Come back tomorrow for another task.'));S.coins+=2}saveSlots();renderUI()}
function questUpdate(type,val){for(let q of S.quests){if(q.done)continue;if(q.type===type&&val>=q.goal){q.done=1;S.coins+=q.reward;setStatus('🏆 Quest complete! +'+q.reward+' coins')}}}
function openChest(b){if(!b.open){b.open=true;addItem('treasure',1);addItem('coin',50);setStatus('📦 Chest opened! Treasure + coins')}else setStatus('📦 Empty chest')}
function discover(){for(const t of S.treasures){if(!t.found&&Math.hypot(t.x-S.x,t.y-S.y)<2){t.found=true;addItem('treasure',2);S.coins+=100;setStatus('💎 Hidden treasure found!')}}for(const r of S.ruins){if(!r.found&&Math.hypot(r.x-S.x,r.y-S.y)<2){r.found=true;addItem('ore',4);setStatus('🏚️ Ruin explored')}}if(Math.hypot(S.x-S.dungeon.x,S.y-S.dungeon.y)<3){S.dungeon.found=true;questUpdate('dungeon',1);if(!S.boss){S.boss={x:S.dungeon.x+1,y:S.dungeon.y,hp:250,max:250,cd:0};setStatus('👹 BOSS ARENA! Defeat the dungeon boss!')}}}
function vehicle(type){if(S.vehicle===type){S.vehicle=null;setStatus('🚶 Dismounted')}else{S.vehicle=type;setStatus('🚗 Mounted '+type+' — movement boosted')}}
function fastTravel(){let w=S.waypoints;if(!w.length)return;let n=w[0];S.x=n.x;S.y=n.y;setStatus('🧭 Fast travelled to '+n.n);saveSlots();renderUI()}
function addWaypoint(){S.waypoints.push({x:S.x,y:S.y,n:'Waypoint '+S.waypoints.length});setStatus('📍 Waypoint added');saveSlots();renderUI()}
function mapModal(){let d=document.createElement('div');d.className='tw5-modal';d.innerHTML='<div class="tw5-modal-box"><h2>🗺️ TineWorld Map</h2><p>Seed: '+S.seed+' • Coordinates: '+S.x+', '+S.y+' • '+S.weather+'</p><canvas id="tw5Map" width="720" height="420"></canvas><div class="tw5-row"><button onclick="tw5Waypoint()">📍 Add Waypoint</button><button onclick="tw5FastTravel()">🧭 Fast Travel Home</button><button onclick="this.closest(\'.tw5-modal\').remove()">Close</button></div></div>';document.body.appendChild(d);let c=el('tw5Map'),x=c.getContext('2d'),sx=c.width/W,sy=c.height/H;for(let y=0;y<H;y++)for(let xx=0;xx<W;xx++){x.fillStyle=COLORS[S.map[y][xx]]||COLORS.grass;x.fillRect(xx*sx,y*sy,sx+1,sy+1)}x.fillStyle='#ffd84a';x.fillRect(S.x*sx-3,S.y*sy-3,7,7);for(let w of S.waypoints){x.fillStyle='#ff5b5b';x.fillRect(w.x*sx-2,w.y*sy-2,5,5)}}
function renderInGameHud(){
  if(!S)return;
  const hp=Math.max(0,Math.min(S.maxhp||100,S.hp||0));
  const n=Math.round(hp/(S.maxhp||100)*10);
  const h=el('tw5Hearts');if(h)h.textContent='♥'.repeat(n)+'♡'.repeat(10-n);
  const hu=el('tw5HudHunger');if(hu)hu.textContent=Math.round(S.hunger||0);
  const st=el('tw5HudStamina');if(st)st.textContent=Math.round(S.stamina||0);
  const bar=el('tw5HotbarInGame');
  if(bar)bar.innerHTML=(S.hotbar||[]).slice(0,9).map((idx,i)=>{const it=S.inventory?.[idx];return '<button class="tw5-hslot '+(i===S.selected?'selected':'')+'" onclick="tw5SelectHot('+i+')"><span>'+(it?(ITEMS[it.id]?.i||'📦'):'')+'</span><small>'+(it?.qty||'')+'</small></button>';}).join('');
}
function renderUI(){renderInGameHud();ensureS();let f=(id,v)=>{let e=el(id);if(e)e.textContent=v};f('twFixHp',Math.round(S.hp));f('twFixCoins',S.coins);f('twFixWood',itemCount('wood'));f('twFixStone',itemCount('stone'));f('twFixOre',itemCount('ore'));f('twFixDay','Day '+S.day+' • '+String(Math.floor(S.time/60)).padStart(2,'0')+':'+String(S.time%60).padStart(2,'0'));let inv=el('tw5Inventory');if(inv)inv.innerHTML=S.inventory.map((s,i)=>'<button class="tw5-slot '+(S.selected===i?'sel':'')+'" data-i="'+i+'">'+(s?ITEMS[s.id].i+'<small>'+s.qty+'</small>':'')+'</button>').join('');if(inv)inv.querySelectorAll('.tw5-slot').forEach(b=>{b.onclick=()=>{let i=+b.dataset.i;if(S.inventory[i]){let slot=S.hotbar.indexOf(i);if(slot<0){S.hotbar[S.selected]=i}else{S.selected=slot}setStatus('🎒 Selected '+ITEMS[S.inventory[i].id].n)}renderUI()}});let hot=el('tw5Hotbar');if(hot)hot.innerHTML=S.hotbar.map((idx,i)=>{let s=S.inventory[idx];return'<button class="tw5-slot '+(S.selected===i?'sel':'')+'" onclick="tw5SelectHot('+i+')">'+(s?ITEMS[s.id].i+'<small>'+s.qty+'</small>':'')+'</button>'}).join('');f('tw5Hunger',Math.round(S.hunger));f('tw5Stamina',Math.round(S.stamina));f('tw5Temp',Math.round(S.temp)+'°C');f('tw5Weather',S.weather);f('tw5Seed',S.seed);f('tw5Coords',S.x+', '+S.y);f('tw5Biome',biomeAt(S.x,S.y,S.seed));f('tw5Vehicle',S.vehicle||'on foot');let q=el('tw5Quests');if(q)q.innerHTML=S.quests.map(a=>'<div class="tw5-quest '+(a.done?'done':'')+'">'+(a.done?'✅':'📜')+' '+a.text+' <b>'+a.reward+'🪙</b></div>').join('');let eq=el('tw5Equip');if(eq)eq.innerHTML=Object.entries(S.equipment).map(([k,v])=>'<button onclick="tw5Equip(\''+k+'\')">'+k+': '+(v?ITEMS[v.id].i:'empty')+'</button>').join('');let save=el('twFixSave');if(save)save.textContent='Saved '+new Date(S.saveAt||Date.now()).toLocaleTimeString();draw()}
function tw5SelectHot(i){S.selected=S.hotbar[i]??0;let it=selectedItem();setStatus(it?'🎒 '+ITEMS[it.id].n:'Empty slot');renderUI()}
function openWorld(){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));let p=el('tineWorldPage');if(!p)return;p.classList.add('active');ensureS();if(S.slot==null)S.slot=0;loadSlot(S.slot);normalize();buildUI();resizeCanvas();cancelAnimationFrame(raf);last=0;raf=requestAnimationFrame(loop);window.scrollTo(0,0)}
function buildUI(){
  let host=document.querySelector('.th-world-pro');
  if(!host||el('tw5Controls'))return;
  let panels=host.querySelector('.tw-world-panels');
  let card=document.createElement('div'); card.id='tw5Controls'; card.className='tw5-extra';
  card.innerHTML='<div class="tw5-top"><div><b>🌎 TineWorld 5.0 Sandbox</b><small>Seeded world • survival • building • villages • dungeons • vehicles</small></div><div class="tw5-bars"><span>🍗 <i id="tw5Hunger">100</i></span><span>⚡ <i id="tw5Stamina">100</i></span><span>🌡️ <i id="tw5Temp">20°C</i></span><span>🌦️ <i id="tw5Weather">clear</i></span></div></div><div class="tw5-actions"><button onclick="tw5Mine()">⛏️ Mine</button><button onclick="tw5Build()">🧱 Place</button><button onclick="tw5Rotate()">🔄 Rotate</button><button onclick="tw5Attack()">⚔️ Attack</button><button onclick="tw5Shoot()">🏹 Bow</button><button onclick="tw5Block()">🛡️ Block</button><button onclick="tw5Eat()">🍎 Eat</button><button onclick="tw5Cook()">🍳 Cook</button><button onclick="tw5Interact()">💬 Talk/Trade</button><button onclick="tw5Discover()">🔎 Explore</button></div><div class="tw5-actions"><button onclick="tw5Map()">🗺️ Map</button><button onclick="tw5Waypoint()">📍 Waypoint</button><button onclick="tw5FastTravel()">🧭 Fast Travel</button><button onclick="tw5CraftMenu()">🔨 Crafting</button><button onclick="tw5Saves()">💾 Worlds</button><button onclick="tw5Chat()">💬 Chat</button></div><div class="tw5-info"><b>📍 <span id="tw5Coords">0,0</span></b> • <b id="tw5Biome">plains</b> • 🎲 <span id="tw5Seed">0</span> • 🚗 <span id="tw5Vehicle">on foot</span></div><div class="tw5-inv-wrap"><h3>🎒 36-Slot Inventory / Hotbar</h3><div id="tw5Inventory" class="tw5-grid"></div><div id="tw5Hotbar" class="tw5-hotbar"></div><div id="tw5Equip" class="tw5-equip"></div></div><div class="tw5-quests"><h3>📜 Quests</h3><div id="tw5Quests"></div></div>';
  panels.appendChild(card);
  let stage=host.querySelector('.tw-fix-stage');
  if(stage&&!el('tw5InGameHud')){
    let hud=document.createElement('div'); hud.id='tw5InGameHud'; hud.className='tw5-ingame-hud';
    hud.innerHTML='<div class="tw5-crosshair">+</div><div class="tw5-status-pill"><span class="tw5-hearts" id="tw5Hearts">♥♥♥♥♥♥♥♥♥♥</span><span class="tw5-mini-stat">🍗 <b id="tw5HudHunger">100</b></span><span class="tw5-mini-stat">⚡ <b id="tw5HudStamina">100</b></span></div><div class="tw5-hotbar-ingame" id="tw5HotbarInGame"></div><div class="tw5-touch-left"><div class="tw5-touch-dpad"><button data-tw-move="0,-1">▲</button><div><button data-tw-move="-1,0">◀</button><button data-tw-jump="1">⤴</button><button data-tw-move="1,0">▶</button></div><button data-tw-move="0,1">▼</button></div></div><div class="tw5-touch-right"><button data-tw-action="attack">⚔️</button><button data-tw-action="mine">⛏️</button><button data-tw-action="build">🧱</button><button data-tw-action="eat">🍎</button><button data-tw-action="block">🛡️</button></div>';
    stage.appendChild(hud); bindInGameHud(hud);
  }
}
function bindInGameHud(hud){
  hud.querySelectorAll('[data-tw-move]').forEach(btn=>{
    const move=btn.dataset.twMove.split(',').map(Number); let timer=0;
    const start=e=>{e.preventDefault();tw5Move(move[0],move[1]);clearInterval(timer);timer=setInterval(()=>tw5Move(move[0],move[1]),120);btn.classList.add('pressed');};
    const stop=()=>{clearInterval(timer);timer=0;btn.classList.remove('pressed');};
    btn.addEventListener('pointerdown',start);btn.addEventListener('pointerup',stop);btn.addEventListener('pointercancel',stop);btn.addEventListener('pointerleave',stop);
  });
  hud.querySelector('[data-tw-jump]')?.addEventListener('pointerdown',e=>{e.preventDefault();tw5Jump();});
  hud.querySelectorAll('[data-tw-action]').forEach(btn=>btn.addEventListener('pointerdown',e=>{e.preventDefault();const fn={attack:tw5Attack,mine:tw5Mine,build:tw5Build,eat:tw5Eat,block:tw5Block}[btn.dataset.twAction];if(fn)fn();btn.classList.add('pressed');setTimeout(()=>btn.classList.remove('pressed'),140)}));
}
function tw5Move(dx,dy){move(dx,dy)}
function tw5Jump(){jump()}
function weatherTick(dt){S.time=(S.time+dt*2)%1440;if(S.time<2){S.day++;S.stats.days=S.day}if(Math.random()<dt*.01)S.weather=['clear','rain','storm','snow'][Math.floor(Math.random()*4)];let b=biomeAt(S.x,S.y,S.seed),base=b==='snow'?-5:b==='desert'?34:b==='jungle'?28:20;S.temp+=(base-S.temp)*dt*.03;S.hunger=Math.max(0,S.hunger-dt*.04);if(S.hunger<15)S.hp=Math.max(0,S.hp-dt*1.5);else if(S.hunger>70&&S.hp<S.maxhp)S.hp=Math.min(S.maxhp,S.hp+dt*.25);if(S.stamina<100)S.stamina=Math.min(100,S.stamina+dt*.8);S.weatherTimer+=dt;if(S.weatherTimer>8){S.weatherTimer=0;aiTick()}if(S.time%30<dt*2)saveSlots()}
function aiTick(){for(let n of S.npcs){n.t=(n.t||0)+1;let target=(Math.floor(S.time/60)+n.x)%3;if(target===0){n.x=clamp(n.x+Math.sign(n.home.x-n.x),1,W-2);n.y=clamp(n.y+Math.sign(n.home.y-n.y),1,H-2)}}for(let a of S.animals){if(Math.random()<.55){let dx=Math.floor(Math.random()*3)-1,dy=Math.floor(Math.random()*3)-1;if(!blocked(a.x+dx,a.y+dy)){a.x+=dx;a.y+=dy}}if(Math.random()<.04)S.breeding++;}if(S.breeding>5){S.breeding=0;let p=freeSpot();S.animals.push({x:p.x,y:p.y,type:'chicken',t:0,energy:100,sex:Math.random()<.5?0:1});setStatus('🐣 Animals reproduced')}
let night=S.time>1140||S.time<360;if(night){for(let e of S.enemies){e.cd-=1;let d=Math.hypot(e.x-S.x,e.y-S.y);if(d<12&&d>1){let dx=Math.sign(S.x-e.x),dy=Math.sign(S.y-e.y);if(Math.random()<.6&&!blocked(e.x+dx,e.y+dy)){e.x+=dx;e.y+=dy}}if(d<1.5&&e.cd<=0){let dmg=S.blocking?2:7;S.hp=Math.max(0,S.hp-dmg);e.cd=2;setStatus('👾 '+e.type+' attacked you')}}}else if(Math.random()<.08){let p=freeSpot();S.enemies.push({x:p.x,y:p.y,type:['goblin','wolf'][Math.floor(Math.random()*2)],hp:40,max:40,cd:0})}
if(S.boss){S.boss.cd-=1;let d=Math.hypot(S.boss.x-S.x,S.boss.y-S.y);if(d<2&&S.boss.cd<=0){S.hp=Math.max(0,S.hp-15);S.boss.cd=2;setStatus('👹 Boss hit you!')}}discover()}
function camera(){let vw=canvas.width/TILE,vh=canvas.height/TILE;return{x:S.x-vw/2,y:S.y-vh/2}}
function draw(){if(!canvas||!ctx)return;let cam=camera(),cw=canvas.width,ch=canvas.height;ctx.clearRect(0,0,cw,ch);let x0=Math.floor(cam.x)-1,y0=Math.floor(cam.y)-1,x1=Math.ceil(cam.x+cw/TILE)+1,y1=Math.ceil(cam.y+ch/TILE)+1;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let t=tile(x,y),px=(x-cam.x)*TILE,py=(y-cam.y)*TILE;ctx.fillStyle=COLORS[t]||'#555';ctx.fillRect(px,py,TILE+1,TILE+1);if(t==='forest'||t==='jungle'){ctx.fillStyle=t==='jungle'?'#165a37':'#246d3a';ctx.beginPath();ctx.arc(px+16,py+12,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6d4b2a';ctx.fillRect(px+13,py+15,6,15)}if(t==='mountain'){ctx.fillStyle='#a7adb2';ctx.beginPath();ctx.moveTo(px+5,py+26);ctx.lineTo(px+16,py+5);ctx.lineTo(px+28,py+26);ctx.fill()}if(t==='ore'){ctx.fillStyle='#c9a1ff';ctx.beginPath();ctx.moveTo(px+6,py+26);ctx.lineTo(px+15,py+5);ctx.lineTo(px+27,py+25);ctx.fill()}if(t==='river'){ctx.strokeStyle='rgba(255,255,255,.25)';ctx.beginPath();ctx.moveTo(px+2,py+8);ctx.lineTo(px+28,py+8);ctx.stroke()}}
for(let b of S.blocks){let px=(b.x-cam.x)*TILE,py=(b.y-cam.y)*TILE;ctx.save();ctx.translate(px+TILE/2,py+TILE/2);ctx.rotate((b.rot||0)*Math.PI/2);ctx.fillStyle=b.type==='glass'?'rgba(170,220,255,.55)':b.type==='door'?'#8b5a2b':b.type==='window'?'#a9e7ff':b.type==='chest'?'#9a642f':b.type==='chair'?'#b7783b':b.type==='torch'?'#f5a623':b.type==='stone'?'#777':'#9a653c';ctx.fillRect(-14,-14,28,b.type==='slab'?13:28);if(b.type==='torch'){ctx.fillStyle='#ffe45c';ctx.beginPath();ctx.arc(0,-15,5,0,7);ctx.fill()}ctx.restore()}
for(let v of S.villages){let px=(v.x-cam.x)*TILE,py=(v.y-cam.y)*TILE;ctx.fillStyle='#d98c48';ctx.fillRect(px+4,py+8,24,20);ctx.fillStyle='#70442c';ctx.beginPath();ctx.moveTo(px+2,py+9);ctx.lineTo(px+16,py-2);ctx.lineTo(px+30,py+9);ctx.fill()}
for(let n of S.npcs)drawChar(n.x,n.y,'#8d6df2',n.name[0],0);for(let a of S.animals)drawChar(a.x,a.y,a.type==='cow'?'#eee':a.type==='deer'?'#9a653b':'#f0a43c',a.type[0].toUpperCase(),Math.sin(a.t||0)*2);for(let e of S.enemies){drawChar(e.x,e.y,e.type==='wolf'?'#65717d':'#d74a5b','!',0);let px=(e.x-cam.x)*TILE,py=(e.y-cam.y)*TILE;ctx.fillStyle='#28141a';ctx.fillRect(px+3,py-5,TILE-6,4);ctx.fillStyle='#ff4154';ctx.fillRect(px+3,py-5,(TILE-6)*Math.max(0,e.hp/e.max),4)}if(S.boss){drawChar(S.boss.x,S.boss.y,'#7d1cff','B',0);let px=(S.boss.x-cam.x)*TILE,py=(S.boss.y-cam.y)*TILE;ctx.fillStyle='#111';ctx.fillRect(px-4,py-10,40,6);ctx.fillStyle='#ff2d68';ctx.fillRect(px-4,py-10,40*Math.max(0,S.boss.hp/S.boss.max),6)}
let p=front(),pcx=(p.x-cam.x)*TILE,pcy=(p.y-cam.y)*TILE;ctx.save();ctx.globalAlpha=.3;ctx.fillStyle='#fff';ctx.fillRect(pcx+2,pcy+2,TILE-4,TILE-4);ctx.restore();drawPlayer(cam);let night=S.time>1140||S.time<360;if(night){ctx.fillStyle='rgba(5,10,28,.48)';ctx.fillRect(0,0,cw,ch)}if(S.weather==='rain'||S.weather==='storm'){ctx.strokeStyle='rgba(180,220,255,.5)';for(let i=0;i<80;i++){let rx=(i*71+performance.now()/4)%cw,ry=(i*43+performance.now()/3)%ch;ctx.beginPath();ctx.moveTo(rx,ry);ctx.lineTo(rx-4,ry+10);ctx.stroke()}}if(S.weather==='snow'){ctx.fillStyle='rgba(255,255,255,.7)';for(let i=0;i<70;i++){let rx=(i*61+performance.now()/7)%cw,ry=(i*37+performance.now()/5)%ch;ctx.fillRect(rx,ry,3,3)}}}
function drawChar(x,y,color,label,bob){let cam=camera(),px=(x-cam.x)*TILE+16,py=(y-cam.y)*TILE+16+bob;ctx.save();ctx.translate(px,py);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,12,11,5,0,0,7);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,-5,9,0,7);ctx.fill();ctx.fillRect(-8,3,16,14);ctx.fillStyle='#fff';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(label,0,0);ctx.restore()}
function drawPlayer(cam){
  if(!Number.isFinite(S.x)||!Number.isFinite(S.y))return;
  let bob=(S.anim?.type==='walk')?Math.sin((S.anim?.t||0)*18)*2:0;
  let px=(S.x-cam.x)*TILE+TILE/2,py=(S.y-cam.y)*TILE+TILE/2+bob;
  if(px<-80||py<-80||px>canvas.width+80||py>canvas.height+80)return;
  ctx.save();ctx.translate(px,py);
  ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(0,17,15,6,0,0,Math.PI*2);ctx.fill();
  if(S.anim?.type==='attack')ctx.rotate(Math.sin((S.anim.t||0)*30)*.35);
  ctx.lineWidth=3;ctx.strokeStyle='#0b1220';
  ctx.fillStyle='#1f6feb';ctx.fillRect(-12,3,24,20);ctx.strokeRect(-12,3,24,20);
  ctx.fillStyle='#ffd18a';ctx.beginPath();ctx.arc(0,-8,12,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#3b2418';ctx.beginPath();ctx.arc(0,-12,12,Math.PI,Math.PI*2);ctx.fill();
  ctx.fillStyle='#111';ctx.beginPath();ctx.arc(-4,-8,2,0,Math.PI*2);ctx.arc(4,-8,2,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle='#111';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-4,-2);ctx.lineTo(4,-2);ctx.stroke();
  ctx.fillStyle='#263238';ctx.fillRect(-8,23,6,7);ctx.fillRect(2,23,6,7);
  if(S.blocking){ctx.fillStyle='#dfe9ff';ctx.strokeStyle='#6ea8ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(16,5,12,0,Math.PI*2);ctx.fill();ctx.stroke()}
  if(S.anim?.type==='attack'){ctx.strokeStyle='#fff3a3';ctx.lineWidth=5;ctx.beginPath();ctx.arc(18,0,25,-.9,.9);ctx.stroke()}
  ctx.restore();
  ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(px-27,py-43,54,14);ctx.fillStyle='#fff';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText('YOU',px,py-32);
}
function loop(ts){let dt=Math.min(.05,(ts-last||16)/1000);last=ts;if(!S)return;S.anim=S.anim||{type:'idle',t:0};S.anim.t+=dt;if(S.fall){S.fall+=dt*2;if(S.fall>=1){S.fall=0;let dmg=Math.max(0,Math.floor(Math.random()*8));if(dmg){S.hp=Math.max(0,S.hp-dmg);setStatus('🪨 Fall damage: '+dmg)}}}weatherTick(dt);draw();raf=requestAnimationFrame(loop)}
function resizeCanvas(){if(!canvas)return;let box=canvas.parentElement.getBoundingClientRect();canvas.width=Math.max(720,Math.floor(box.width));canvas.height=Math.max(420,Math.floor(Math.min(box.width*.58,680)));if(canvas.width>1200)canvas.width=1200}
const CSS=`#tineWorldPage .th-world-pro{max-width:1200px;margin:auto}.tw5-extra{margin:12px 0}.tw5-top,.tw5-actions,.tw5-info,.tw5-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.tw5-top{justify-content:space-between;background:linear-gradient(135deg,#10243b,#183a3d);padding:14px;border-radius:18px;color:#fff}.tw5-top small{display:block;opacity:.72}.tw5-bars{display:flex;gap:8px;flex-wrap:wrap}.tw5-bars span{background:rgba(255,255,255,.1);padding:6px 9px;border-radius:10px}.tw5-actions{margin:8px 0}.tw5-actions button,.tw5-equip button,.tw5-row button{border:0;border-radius:12px;padding:9px 11px;background:#182b43;color:#fff;font-weight:800}.tw5-info{padding:8px 10px;border-radius:12px;background:rgba(50,120,100,.12)}.tw5-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:5px}.tw5-hotbar{display:flex;gap:6px;margin-top:8px;overflow:auto}.tw5-slot{min-width:45px;height:45px;border:1px solid rgba(255,255,255,.15);border-radius:9px;background:#132338;color:#fff;position:relative;font-size:19px}.tw5-slot.sel{outline:3px solid #ffd84a}.tw5-slot small{position:absolute;right:3px;bottom:1px;font-size:10px}.tw5-equip{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.tw5-quest{padding:6px;border-bottom:1px solid rgba(255,255,255,.08)}.tw5-quest.done{opacity:.6}.tw5-controls{text-align:center;margin-top:10px}.tw5-dpad button{width:52px;height:42px;margin:2px;border:0;border-radius:12px;background:#17314b;color:#fff;font-size:20px}.tw5-modal{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:999999;display:grid;place-items:center;padding:16px}.tw5-modal-box{max-width:900px;width:100%;max-height:92vh;overflow:auto;background:#102238;color:#fff;padding:18px;border-radius:20px}.tw5-craft{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.tw5-craft button{padding:12px;border:0;border-radius:12px;background:#1d3856;color:#fff;font-weight:800}.tw5-modal canvas{width:100%;height:auto;border-radius:12px}.tw5-inv-wrap{margin-top:10px}.tw5-inv-wrap h3,.tw5-quests h3{margin:8px 0}@media(max-width:700px){.tw5-grid{grid-template-columns:repeat(6,1fr)}.tw5-craft{grid-template-columns:repeat(2,1fr)}.tw5-actions button{flex:1 1 28%}#twFixCanvas{touch-action:none}.tw5-top{font-size:13px}}
@media(orientation:landscape){#tineWorldPage .th-world-pro{max-width:1400px}.tw5-extra{font-size:13px}.tw5-grid{grid-template-columns:repeat(18,1fr)}}`;

let dragInv=null;
document.addEventListener('pointerdown',function(e){let b=e.target.closest?.('#tw5Inventory .tw5-slot');if(b)dragInv=+b.dataset.i});
document.addEventListener('pointerup',function(e){if(dragInv==null)return;let b=e.target.closest?.('#tw5Inventory .tw5-slot');if(b){let j=+b.dataset.i;if(j!==dragInv){let t=S.inventory[dragInv];S.inventory[dragInv]=S.inventory[j];S.inventory[j]=t;saveSlots();renderUI();setStatus('🎒 Items swapped')}}dragInv=null});
function twSetFullscreenButton(active){const b=el('twFullscreenBtn');if(b){b.innerHTML=active?'⛶ <span>Exit Fullscreen</span>':'⛶ <span>Fullscreen</span>';}}
async function twToggleFullscreen(){try{if(!document.fullscreenElement){const target=document.documentElement;if(target.requestFullscreen)await target.requestFullscreen({navigationUI:'hide'});else if(target.webkitRequestFullscreen)target.webkitRequestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape').catch(()=>{});document.body.classList.add('tw-android-immersive');twSetFullscreenButton(true);setStatus('⛶ Fullscreen + landscape enabled.');}else{if(document.exitFullscreen)await document.exitFullscreen();else if(document.webkitExitFullscreen)document.webkitExitFullscreen();document.body.classList.remove('tw-android-immersive');twSetFullscreenButton(false);setStatus('↩️ Fullscreen closed.');}}catch(e){document.body.classList.add('tw-android-immersive');setStatus('⛶ Immersive layout enabled. Android WebView fullscreen requires WebChromeClient support.');}}
function twSetLandscapeButton(active){const b=el('twLandscapeBtn');const page=el('tineWorldPage');if(b){b.innerHTML=active?'↩️ <span>Portrait</span>':'📱↔️ <span>Landscape</span>';}page?.classList.toggle('tw-landscape-active',!!active);setTimeout(()=>window.dispatchEvent(new Event('resize')),80)}
async function twToggleLandscape(){const page=el('tineWorldPage');if(!page)return;const active=page.classList.contains('tw-landscape-active');if(!active){twSetLandscapeButton(true);await screen.orientation?.lock?.('landscape').catch(()=>{});setStatus('📱 Landscape layout enabled.');}else{screen.orientation?.unlock?.();twSetLandscapeButton(false);setStatus('↩️ Portrait layout restored.');}}
window.addEventListener('fullscreenchange',()=>twSetFullscreenButton(!!document.fullscreenElement));
window.twFixMove=tw5Move;window.twFixMine=tw5Mine;window.twFixBuild=tw5Build;window.twFixAttack=tw5Attack;window.twFixEat=tw5Eat;window.twFixCraft=tw5Craft;window.twFixNew=tw5NewWorld;window.twFixSaveWorld=saveSlots;window.twFixBack=function(){cancelAnimationFrame(raf);document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));el('games')?.classList.add('active')};window.openTineWorld=openWorld;window.twToggleFullscreen=twToggleFullscreen;window.twToggleLandscape=twToggleLandscape;
window.tw5Mine=tw5Mine;window.tw5Build=tw5Build;window.tw5Rotate=tw5Rotate;window.tw5Copy=tw5Copy;window.tw5Paste=tw5Paste;window.tw5Attack=tw5Attack;window.tw5Shoot=tw5Shoot;window.tw5Block=tw5Block;window.tw5Eat=tw5Eat;window.tw5Cook=tw5Cook;window.tw5Interact=tw5Interact;window.tw5Discover=tw5Discover;window.tw5Map=tw5Map;window.tw5Waypoint=tw5Waypoint;window.tw5FastTravel=tw5FastTravel;window.tw5Vehicle=tw5Vehicle;window.tw5CraftMenu=tw5CraftMenu;window.tw5Craft=craft;window.tw5Saves=tw5Saves;window.tw5Load=tw5Load;window.tw5NewWorld=tw5NewWorld;window.tw5Rename=tw5Rename;window.tw5Delete=tw5Delete;window.tw5Chat=tw5Chat;window.tw5SelectHot=tw5SelectHot;window.tw5Equip=equip;window.tw5Jump=tw5Jump;
window.addEventListener('resize',resizeCanvas);document.addEventListener('keydown',function(e){if(!el('tineWorldPage')?.classList.contains('active'))return;let k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();let m={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]};if(m[k]){S.dir=m[k][0]||S.dir;tw5Move(...m[k])}if(k===' ')tw5Jump();if(k==='f')tw5Attack();if(k==='q')tw5Mine();if(k==='b')tw5Build();if(k==='r')tw5Shoot();if(k==='e')tw5Interact();if(k==='shift')tw5Block()});
window.addEventListener('pointerdown',e=>{if(!el('tineWorldPage')?.classList.contains('active'))return;if(e.target.closest('#twFixCanvas')){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;let cam=camera(),tx=Math.floor(cam.x+x/TILE),ty=Math.floor(cam.y+y/TILE);if(Math.hypot(tx-S.x,ty-S.y)<5){S.dir=tx<S.x?-1:1;setStatus('🎯 Target '+tx+','+ty)}}});
})();
